services:
  - type: web
    name: consoltech-api
    env: docker
    dockerfilePath: ./backend/Consoltech.AdminApi/Dockerfile
    dockerContext: ./backend/Consoltech.AdminApi
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: consoltech-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ISSUER
        value: Consoltech.AdminApi
      - key: JWT_AUDIENCE
        value: Consoltech.Frontend

databases:
  - name: consoltech-db
    plan: free
    region: frankfurt
    databaseName: consoltech
    user: consoltech_user
